name: google_directions_api
version: 1.0.0
homepage: https://github.com/marchdev-tk/google_directions_api
description: A starting point for Dart libraries or applications.

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_polyline_algorithm: ^1.0.0
  google_maps_flutter: ^0.5.24+1
  http: ^0.12.0+4
  flinq: ^1.1.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
